version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: trilha-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: trilha-api
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432

volumes:
  postgres_data:
