// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"trilha-api/internal/account/handler"
	"trilha-api/internal/account/repository"
	"trilha-api/internal/account/use_case"
	"trilha-api/internal/shared/database/sqlc"
)

// Injectors from account_wire.go:

func NewAccountHandler(db2 *db.Queries) *handler.AccountHandler {
	accountRepository := repository.New(db2)
	accountUseCase := usecase.New(accountRepository)
	accountHandler := handler.New(accountUseCase)
	return accountHandler
}

// account_wire.go:

var set_account_repository_dependency = wire.NewSet(repository.New, wire.Bind(new(repository.AccountRepositoryInterface), new(*repository.AccountRepository)))
